version: '3.8'
services:
  db:
    image: postgres
    restart: always
    ports:
      - ${DB_HOST_PORT}:${DB_CONTAINER_PORT}
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_POSTGRES_DB}