name: Test

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Start server
        run: |
          npm start &
          sleep 10 # Espera 10 segundos para que el servidor se inicie correctamente

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          start: npm run cypress
