name: Test

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Close port 3000
        run: |
          sudo apt-get install lsof -y
          PORT_PID=$(lsof -t -i :3000)
          if [[ -n "$PORT_PID" ]]; then
            echo "Killing process $PORT_PID"
            kill $PORT_PID
          else
            echo "Port 3000 is not in use."
          fi

      - name: Start server
        run: |
          npm start &
          sleep 10 # Wait 10 seconds for the server to start correctly.

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          start: npm run cypress

      - name: Close port 3000
        run: |
          sudo apt-get install lsof -y
          PORT_PID=$(lsof -t -i :3000)
          if [[ -n "$PORT_PID" ]]; then
            echo "Killing process $PORT_PID"
            kill $PORT_PID
          else
            echo "Port 3000 is not in use."
          fi
